---
anchors:
  thresholds-operstate: &thresholds-operstate
    - { color: "red", level: 0 }
    - { color: "green", level: 1 }
  thresholds-traffic: &thresholds-traffic
    - { color: "gray", level: 0 }
    - { color: "green", level: 100 }
    - { color: "yellow", level: 50000 }
    - { color: "orange", level: 500000 }
    - { color: "red", level: 5000000 }
  label-config: &label-config
    separator: "replace"
    units: "bps"
    decimalPoints: 1
    valueMappings:
      - { valueMax: 99, text: "\u200B" }
cellIdPreamble: "cell-"
cells:
  "wan-core:e1-1":
    dataRef: "oper-state:wan-core:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "pe1:e1-32":
    dataRef: "oper-state:pe1:e1-32"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:wan-core:e1-1:pe1:e1-32":
    dataRef: "wan-core:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:pe1:e1-32:wan-core:e1-1":
    dataRef: "pe1:e1-32:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "wan-core:e1-2":
    dataRef: "oper-state:wan-core:e1-2"
    fillColor:
      thresholds: *thresholds-operstate
  "pe2:e1-32":
    dataRef: "oper-state:pe2:e1-32"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:wan-core:e1-2:pe2:e1-32":
    dataRef: "wan-core:e1-2:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:pe2:e1-32:wan-core:e1-2":
    dataRef: "pe2:e1-32:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "wan-core:e1-10":
    dataRef: "oper-state:wan-core:e1-10"
    fillColor:
      thresholds: *thresholds-operstate
  "server-wan:eth1":
    dataRef: "oper-state:server-wan:eth1"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:wan-core:e1-10:server-wan:eth1":
    dataRef: "wan-core:e1-10:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:server-wan:eth1:wan-core:e1-10":
    dataRef: "server-wan:eth1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "pe1:e1-1":
    dataRef: "oper-state:pe1:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "b-leaf1:e1-32":
    dataRef: "oper-state:b-leaf1:e1-32"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:pe1:e1-1:b-leaf1:e1-32":
    dataRef: "pe1:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:b-leaf1:e1-32:pe1:e1-1":
    dataRef: "b-leaf1:e1-32:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "pe2:e1-1":
    dataRef: "oper-state:pe2:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "b-leaf2:e1-32":
    dataRef: "oper-state:b-leaf2:e1-32"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:pe2:e1-1:b-leaf2:e1-32":
    dataRef: "pe2:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:b-leaf2:e1-32:pe2:e1-1":
    dataRef: "b-leaf2:e1-32:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "b-leaf1:e1-10":
    dataRef: "oper-state:b-leaf1:e1-10"
    fillColor:
      thresholds: *thresholds-operstate
  "fw1:eth1":
    dataRef: "oper-state:fw1:eth1"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:b-leaf1:e1-10:fw1:eth1":
    dataRef: "b-leaf1:e1-10:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:fw1:eth1:b-leaf1:e1-10":
    dataRef: "fw1:eth1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "b-leaf2:e1-10":
    dataRef: "oper-state:b-leaf2:e1-10"
    fillColor:
      thresholds: *thresholds-operstate
  "fw2:eth1":
    dataRef: "oper-state:fw2:eth1"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:b-leaf2:e1-10:fw2:eth1":
    dataRef: "b-leaf2:e1-10:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:fw2:eth1:b-leaf2:e1-10":
    dataRef: "fw2:eth1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "b-leaf1:e1-1":
    dataRef: "oper-state:b-leaf1:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "spine1:e1-31":
    dataRef: "oper-state:spine1:e1-31"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:b-leaf1:e1-1:spine1:e1-31":
    dataRef: "b-leaf1:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:spine1:e1-31:b-leaf1:e1-1":
    dataRef: "spine1:e1-31:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "b-leaf1:e1-2":
    dataRef: "oper-state:b-leaf1:e1-2"
    fillColor:
      thresholds: *thresholds-operstate
  "spine2:e1-31":
    dataRef: "oper-state:spine2:e1-31"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:b-leaf1:e1-2:spine2:e1-31":
    dataRef: "b-leaf1:e1-2:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:spine2:e1-31:b-leaf1:e1-2":
    dataRef: "spine2:e1-31:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "b-leaf2:e1-1":
    dataRef: "oper-state:b-leaf2:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "spine1:e1-32":
    dataRef: "oper-state:spine1:e1-32"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:b-leaf2:e1-1:spine1:e1-32":
    dataRef: "b-leaf2:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:spine1:e1-32:b-leaf2:e1-1":
    dataRef: "spine1:e1-32:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "b-leaf2:e1-2":
    dataRef: "oper-state:b-leaf2:e1-2"
    fillColor:
      thresholds: *thresholds-operstate
  "spine2:e1-32":
    dataRef: "oper-state:spine2:e1-32"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:b-leaf2:e1-2:spine2:e1-32":
    dataRef: "b-leaf2:e1-2:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:spine2:e1-32:b-leaf2:e1-2":
    dataRef: "spine2:e1-32:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "spine1:e1-1":
    dataRef: "oper-state:spine1:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf1:e1-49":
    dataRef: "oper-state:leaf1:e1-49"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:spine1:e1-1:leaf1:e1-49":
    dataRef: "spine1:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf1:e1-49:spine1:e1-1":
    dataRef: "leaf1:e1-49:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "spine1:e1-2":
    dataRef: "oper-state:spine1:e1-2"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf2:e1-49":
    dataRef: "oper-state:leaf2:e1-49"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:spine1:e1-2:leaf2:e1-49":
    dataRef: "spine1:e1-2:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf2:e1-49:spine1:e1-2":
    dataRef: "leaf2:e1-49:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "spine1:e1-3":
    dataRef: "oper-state:spine1:e1-3"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf3:e1-49":
    dataRef: "oper-state:leaf3:e1-49"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:spine1:e1-3:leaf3:e1-49":
    dataRef: "spine1:e1-3:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf3:e1-49:spine1:e1-3":
    dataRef: "leaf3:e1-49:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "spine1:e1-4":
    dataRef: "oper-state:spine1:e1-4"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf4:e1-49":
    dataRef: "oper-state:leaf4:e1-49"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:spine1:e1-4:leaf4:e1-49":
    dataRef: "spine1:e1-4:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf4:e1-49:spine1:e1-4":
    dataRef: "leaf4:e1-49:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "spine2:e1-1":
    dataRef: "oper-state:spine2:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf1:e1-50":
    dataRef: "oper-state:leaf1:e1-50"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:spine2:e1-1:leaf1:e1-50":
    dataRef: "spine2:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf1:e1-50:spine2:e1-1":
    dataRef: "leaf1:e1-50:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "spine2:e1-2":
    dataRef: "oper-state:spine2:e1-2"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf2:e1-50":
    dataRef: "oper-state:leaf2:e1-50"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:spine2:e1-2:leaf2:e1-50":
    dataRef: "spine2:e1-2:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf2:e1-50:spine2:e1-2":
    dataRef: "leaf2:e1-50:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "spine2:e1-3":
    dataRef: "oper-state:spine2:e1-3"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf3:e1-50":
    dataRef: "oper-state:leaf3:e1-50"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:spine2:e1-3:leaf3:e1-50":
    dataRef: "spine2:e1-3:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf3:e1-50:spine2:e1-3":
    dataRef: "leaf3:e1-50:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "spine2:e1-4":
    dataRef: "oper-state:spine2:e1-4"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf4:e1-50":
    dataRef: "oper-state:leaf4:e1-50"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:spine2:e1-4:leaf4:e1-50":
    dataRef: "spine2:e1-4:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf4:e1-50:spine2:e1-4":
    dataRef: "leaf4:e1-50:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "server1:eth1":
    dataRef: "oper-state:server1:eth1"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf1:e1-1":
    dataRef: "oper-state:leaf1:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:server1:eth1:leaf1:e1-1":
    dataRef: "server1:eth1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf1:e1-1:server1:eth1":
    dataRef: "leaf1:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "server1:eth2":
    dataRef: "oper-state:server1:eth2"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf2:e1-1":
    dataRef: "oper-state:leaf2:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:server1:eth2:leaf2:e1-1":
    dataRef: "server1:eth2:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf2:e1-1:server1:eth2":
    dataRef: "leaf2:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "server2:eth1":
    dataRef: "oper-state:server2:eth1"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf3:e1-1":
    dataRef: "oper-state:leaf3:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:server2:eth1:leaf3:e1-1":
    dataRef: "server2:eth1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf3:e1-1:server2:eth1":
    dataRef: "leaf3:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "server2:eth2":
    dataRef: "oper-state:server2:eth2"
    fillColor:
      thresholds: *thresholds-operstate
  "leaf4:e1-1":
    dataRef: "oper-state:leaf4:e1-1"
    fillColor:
      thresholds: *thresholds-operstate
  "link_id:server2:eth2:leaf4:e1-1":
    dataRef: "server2:eth2:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
  "link_id:leaf4:e1-1:server2:eth2":
    dataRef: "leaf4:e1-1:out"
    label: *label-config
    strokeColor:
      thresholds: *thresholds-traffic
